### PR TITLE
Add git plugin

### PR DESCRIPTION
**Pull request by idanski**

### CODE REVIEW

**Comment by idanski** [comment]
@drrlvn did you miss this one?

**Comment by drrlvn** [comment]
Actually I wanted to think about this and then forgot about it, sorry about that!

I wouldn't mind adding the plugin since it only adds aliases but I don't know that I like adding the function - it seems specific to some use case and maybe would be better in your git config file and not a general fish config?

**Comment by idanski** [comment]
I don't mind having it locally..

I just thought the function is general enough and would be useful to others as I find myself re-adding it whenever I install a new system.
(I don't use emacs and magit - at least not yet.. ;) )

So should I remove the function from the PR?

**Comment by drrlvn** [comment]
> I don't mind having it locally..

We have a git config we share, maybe you can use that: https://github.com/drrlvn/config-files/blob/master/gitconfig

> So should I remove the function from the PR?

Yes please.

**Comment by idanski** [comment]
sorry for the delay @drrlvn .

**Comment by drrlvn** [comment]
@idanski No problem, there's no rush.

Please change the commit message and I'll merge.

**Comment by idanski** [comment]
@drrlvn  done :)

**Pull request merged**
